"use client";

import React, { useCallback } from 'react';
import Spline from '@splinetool/react-spline';
import type { Application } from '@splinetool/runtime';

/**
 * Suppress Three.js "potentially uninitialized variable" shader warnings
 * that originate from Spline's internal shader compiler. The f_blur variable
 * is auto-generated by Spline's runtime and is benign, but the warning floods
 * the console.
 */
function suppressShaderWarnings(app: Application) {
  // Spline manages its own WebGL renderer internally.
  // Cast to access the renderer to disable shader-error checks.
  const splineApp = app as unknown as { renderer?: { debug?: { checkShaderErrors?: boolean } } };
  if (splineApp.renderer?.debug) {
    splineApp.renderer.debug.checkShaderErrors = false;
  }
}

function HeroSplineBackground() {
  const handleLoad = useCallback((app: Application) => {
    suppressShaderWarnings(app);
  }, []);

  return (
    <div style={{
      position: 'relative',
      width: '100%',
      height: '100vh',
      pointerEvents: 'auto',
      overflow: 'hidden',
    }}>
      <Spline
        style={{
          width: '100%',
          height: '100vh',
          pointerEvents: 'auto',
        }}
        scene="https://prod.spline.design/dJqTIQ-tE3ULUPMi/scene.splinecode"
        onLoad={handleLoad}
      />
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          width: '100%',
          height: '100vh',
          background: `
            linear-gradient(to right, rgba(0, 0, 0, 0.8), transparent 30%, transparent 70%, rgba(0, 0, 0, 0.8)),
            linear-gradient(to bottom, transparent 50%, rgba(0, 0, 0, 0.9))
          `,
          pointerEvents: 'none',
        }}
      />
    </div>
  );
}

export { HeroSplineBackground };
